version: 1.0.{build}

install:
- appveyor DownloadFile https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
- rustup-init.exe -y
- del rustup-init.exe
- set Path=%Path%;C:\Users\appveyor\.cargo\bin

build_script:
- cargo build --release

artifacts:
- path: target\release\reportyatsu.exe
