[package]
name = "reportyatsu"
version = "0.2.0"
authors = ["azyobuzin <azyobuzin@users.sourceforge.jp>"]
publish = false

[dependencies]
clap = "2.18.0"
cssparser = "0.7.0"
html5ever = "0.9.0"
html5ever-atoms = "0.1.2"
kuchiki = "0.4.0"
selectors = "0.14"
